const TEAM_NAMES_ZH = {
  // 歐洲
  "Germany": "德國",
  "France": "法國",
  "Spain": "西班牙",
  "Portugal": "葡萄牙",
  "England": "英格蘭",
  "Netherlands": "荷蘭",
  "Belgium": "比利時",
  "Croatia": "克羅埃西亞",
  "Denmark": "丹麥",
  "Switzerland": "瑞士",
  "Poland": "波蘭",
  "Serbia": "塞爾維亞",
  "Wales": "威爾斯",
  "Italy": "義大利",
  "Austria": "奧地利",
  "Ukraine": "烏克蘭",
  "Sweden": "瑞典",
  "Norway": "挪威",
  "Scotland": "蘇格蘭",
  "Turkey": "土耳其",
  "Hungary": "匈牙利",
  "Slovakia": "斯洛伐克",
  "Romania": "羅馬尼亞",
  "Greece": "希臘",
  "Czech Republic": "捷克",
  "Slovenia": "斯洛維尼亞",
  "Albania": "阿爾巴尼亞",
  "Czechia": "捷克",
  "Bosnia-Herzegovina": "波赫",
  "Bosnia & Herzegovina": "波斯尼亞和黑塞哥維那",
  "Curaçao": "庫拉索",
  // 南美
  "Brazil": "巴西",
  "Argentina": "阿根廷",
  "Uruguay": "烏拉圭",
  "Colombia": "哥倫比亞",
  "Ecuador": "厄瓜多",
  "Chile": "智利",
  "Paraguay": "巴拉圭",
  "Peru": "秘魯",
  "Venezuela": "委內瑞拉",
  "Bolivia": "玻利維亞",
  "Haiti": "海地",
  // 北中美
  "USA": "美國",
  "United States": "美國",
  "Mexico": "墨西哥",
  "Canada": "加拿大",
  "Costa Rica": "哥斯大黎加",
  "Panama": "巴拿馬",
  "Honduras": "宏都拉斯",
  "Jamaica": "牙買加",

  // 亞洲
  "Japan": "日本",
  "South Korea": "南韓",
  "Korea Republic": "南韓",
  "Australia": "澳洲",
  "Iran": "伊朗",
  "Saudi Arabia": "沙烏地阿拉伯",
  "Qatar": "卡達",
  "China PR": "中國",
  "China": "中國",
  "Iraq": "伊拉克",
  "UAE": "阿聯",
  "Uzbekistan": "烏茲別克",
  "Jordan": "約旦",
  "Bahrain": "巴林",
  "Oman": "阿曼",
  "Kuwait": "科威特",

  // 非洲
  "Morocco": "摩洛哥",
  "Senegal": "塞內加爾",
  "Ghana": "加納",
  "Cameroon": "喀麥隆",
  "Tunisia": "突尼西亞",
  "Nigeria": "奈及利亞",
  "Egypt": "埃及",
  "Algeria": "阿爾及利亞",
  "Ivory Coast": "象牙海岸",
  "Côte d'Ivoire": "象牙海岸",
  "Mali": "馬利",
  "Burkina Faso": "布吉納法索",
  "South Africa": "南非",
  "Congo DR": "剛果",
  "Zambia": "尚比亞",
  "Tanzania": "坦尚尼亞",
  "Cape Verde Islands": "佛得角共和國",
  // 大洋洲
  "New Zealand": "紐西蘭",
  "Fiji": "斐濟",
};

function getTeamNameZh(englishName) {
  return TEAM_NAMES_ZH[englishName] || englishName; // 找不到就回傳英文
}

module.exports = { TEAM_NAMES_ZH, getTeamNameZh };